// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// COleEdit wrapper class

class COleEdit : public CWnd
{
protected:
	DECLARE_DYNCREATE(COleEdit)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa2e1c1d, 0x5f28, 0x4850, { 0x91, 0x29, 0x8d, 0x55, 0xe9, 0xb6, 0xbb, 0x6d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetBNumbers();
	void SetBNumbers(BOOL);
	BOOL GetBText();
	void SetBText(BOOL);

// Operations
public:
	void AboutBox();
};
