// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRecordset1 wrapper class

class CRecordset1 : public COleDispatchDriver
{
public:
	CRecordset1() {}		// Calls COleDispatchDriver default constructor
	CRecordset1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRecordset1(const CRecordset1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
