// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "magicbox.h"

/////////////////////////////////////////////////////////////////////////////
// CMagicBox

IMPLEMENT_DYNCREATE(CMagicBox, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMagicBox properties

/////////////////////////////////////////////////////////////////////////////
// CMagicBox operations

void CMagicBox::SetBackColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(DISPID_BACKCOLOR, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long CMagicBox::GetBackColor()
{
	unsigned long result;
	InvokeHelper(DISPID_BACKCOLOR, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMagicBox::SetFillColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xfffffe02, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long CMagicBox::GetFillColor()
{
	unsigned long result;
	InvokeHelper(0xfffffe02, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
