#if !defined(AFX_MAGICBOX_H__41ED1560_A205_4862_A786_582046F6AD5B__INCLUDED_)
#define AFX_MAGICBOX_H__41ED1560_A205_4862_A786_582046F6AD5B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMagicBox wrapper class

class CMagicBox : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMagicBox)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9c4a11f3, 0x7aa3, 0x4587, { 0xbb, 0x40, 0x7a, 0x53, 0x69, 0x6, 0x31, 0x37 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetFillColor(unsigned long newValue);
	unsigned long GetFillColor();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MAGICBOX_H__41ED1560_A205_4862_A786_582046F6AD5B__INCLUDED_)
